#!/bin/bash

set -e

echo "1: ${1}"
echo "2: ${3}"
echo "3: ${2}"
#cd "${1}"

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

echo "testing"
set +x
# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-test.XXXXXX)

cat > "${payload}" <&0

echo "payload : ${payload}"

timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
echo "timestamp"

build_name="$(jq '(.params.build_name // null)' < "${payload}")"
echo "build_name"

metadata=""
echo "build metadata"
  metadata="$(cat <<EOF
{
  "metadata": [
    {"name": "build_name",          "value": ${build_name}            },
  ]
}
EOF
  )"
echo "$timestamp $metadata"  >&3
